### ISSUE TITLE
Epic: Set up API

### ISSUE THREAD

**Issue by ashley-telsan** [ashley-telsan/telsan-recipe-book#1]
## Epic Goals
- [ ] #5
  - [ ] Set up Apollo
  - [ ] Set up Express middleware
  - [ ] Dockerize API
- [ ] Set up Postgres database
- [ ] Set up linting and formatting
- [ ] Set up basic testing with Jest
- [ ] Set up GitHub actions for linting, formatting, and testing
- [ ] Set up pre-commit hooks for linting, formatting, and testing
